//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTW.Data.Analys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvanceExtension
    {
        public AdvanceExtension()
        {
            this.AnswerExtension = new HashSet<AnswerExtension>();
        }
    
        public int AdvanceExtID { get; set; }
        public string Active { get; set; }
        public string Number { get; set; }
        public int IntervalLow { get; set; }
        public int IntervalHigh { get; set; }
        public bool Subscribed { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> ChangedDate { get; set; }
        public Nullable<int> ChangedBy { get; set; }
        public short AnalysisView { get; set; }
        public bool AnalysisRawdata { get; set; }
    
        public virtual ICollection<AnswerExtension> AnswerExtension { get; set; }
    }
}
