//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTW.Data.Analys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnswerExtension
    {
        public AnswerExtension()
        {
            this.CallData = new HashSet<CallData>();
        }
    
        public int AnswerExtID { get; set; }
        public string Number { get; set; }
        public int AdvanceExtId { get; set; }
        public System.DateTime CreationDate { get; set; }
    
        public virtual AdvanceExtension AdvanceExtension { get; set; }
        public virtual ICollection<CallData> CallData { get; set; }
    }
}
