//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTW.Data.Analys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AreaCode
    {
        public string AreaCode1 { get; set; }
        public string Area { get; set; }
        public short RegionId { get; set; }
        public int AreaId { get; set; }
    
        public virtual Region Region { get; set; }
    }
}
