//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTW.Data.Analys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CallType
    {
        public CallType()
        {
            this.CallData = new HashSet<CallData>();
        }
    
        public short ID { get; set; }
        public string CallType1 { get; set; }
    
        public virtual ICollection<CallData> CallData { get; set; }
    }
}
