//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTW.Data.Analys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CallData
    {
        public int AnswerExtId { get; set; }
        public System.DateTime CallDateTime { get; set; }
        public string AreaCode { get; set; }
        public string Extension { get; set; }
        public int CallDuration { get; set; }
        public short CallTypeID { get; set; }
        public int CallDataID { get; set; }
        public short AreaId { get; set; }
        public System.DateTime CallDate { get; set; }
        public Nullable<short> IntervalId { get; set; }
    
        public virtual AnswerExtension AnswerExtension { get; set; }
        public virtual CallType CallType { get; set; }
    }
}
