//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTW.Data.Analys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyInfo
    {
        public int CompanyId { get; set; }
        public string OrgNr { get; set; }
        public string CompanyName { get; set; }
        public Nullable<int> GroupId { get; set; }
        public string EDI { get; set; }
        public string Country { get; set; }
        public string SamRefKod { get; set; }
        public string UnitNo { get; set; }
        public string OLD_ContactName { get; set; }
        public string OLD_ContactTelNo { get; set; }
        public string OLD_ContactEmail { get; set; }
        public Nullable<int> OLD_ContactUserId { get; set; }
        public string Date { get; set; }
        public string CustNo { get; set; }
        public bool ActiveVIP { get; set; }
        public bool ActiveStat { get; set; }
        public Nullable<bool> ActiveCpa { get; set; }
        public bool New { get; set; }
        public string PhoneKey { get; set; }
        public bool ExtendedMulti { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> ChangedDate { get; set; }
        public Nullable<int> ChangedBy { get; set; }
        public Nullable<System.DateTime> SystemChangedDate { get; set; }
        public Nullable<int> UserIdA { get; set; }
        public Nullable<int> UserIdD { get; set; }
        public int UserIdCpa { get; set; }
    
        public virtual GroupInfo GroupInfo { get; set; }
    }
}
