//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTW.Data.Analys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FictiveOrgNr
    {
        public int Counter { get; set; }
        public string ForeignOrgNr { get; set; }
        public string FictiveOrgNr1 { get; set; }
        public System.DateTime SkapadDatum { get; set; }
    }
}
