//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTW.Data.Analys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupInfo
    {
        public GroupInfo()
        {
            this.CompanyInfo = new HashSet<CompanyInfo>();
        }
    
        public int GroupId { get; set; }
        public string GroupCode { get; set; }
        public string GroupName { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> ChangedDate { get; set; }
        public Nullable<int> ChangedBy { get; set; }
    
        public virtual ICollection<CompanyInfo> CompanyInfo { get; set; }
    }
}
