//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTW.Data.Analys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interval
    {
        public int Interval1 { get; set; }
        public string Text { get; set; }
        public short IntervalId { get; set; }
    }
}
