//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTW.Data.Analys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Region
    {
        public Region()
        {
            this.AreaCode = new HashSet<AreaCode>();
        }
    
        public Nullable<short> SortOrder { get; set; }
        public short RegionId { get; set; }
        public string Region1 { get; set; }
    
        public virtual ICollection<AreaCode> AreaCode { get; set; }
    }
}
