//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTW.Data.Analys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vCallData
    {
        public string AnswerExtension { get; set; }
        public string Extension { get; set; }
        public string CallDate { get; set; }
        public string CallTime { get; set; }
        public int CallDuration { get; set; }
        public string CallType { get; set; }
        public string area { get; set; }
        public string Region { get; set; }
        public int AdvanceExtID { get; set; }
        public int AnswerExtID { get; set; }
        public System.DateTime CallDateTime { get; set; }
        public string Ort { get; set; }
    }
}
