//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telia.NTW.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyInfo
    {
        public CompanyInfo()
        {
            this.Users = new HashSet<User>();
            this.Roles = new HashSet<Role>();
            this.AdvanceExtensions = new HashSet<AdvanceExtension>();
        }
    
        public int CompanyId { get; set; }
        public string OrgNr { get; set; }
        public string CompanyName { get; set; }
        public Nullable<int> GroupId { get; set; }
        public string EDI { get; set; }
        public string Country { get; set; }
        public string SamRefKod { get; set; }
        public string UnitNo { get; set; }
        public string OLD_ContactName { get; set; }
        public string OLD_ContactTelNo { get; set; }
        public string OLD_ContactEmail { get; set; }
        public Nullable<int> OLD_ContactUserId { get; set; }
        public string Date { get; set; }
        public string CustNo { get; set; }
        public Nullable<bool> ActiveVIP { get; set; }
        public Nullable<bool> ActiveStat { get; set; }
        public Nullable<bool> ActiveCpa { get; set; }
        public Nullable<bool> New { get; set; }
        public string PhoneKey { get; set; }
        public Nullable<bool> ExtendedMulti { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> ChangedDate { get; set; }
        public Nullable<int> ChangedBy { get; set; }
        public Nullable<System.DateTime> SystemChangedDate { get; set; }
        public Nullable<int> UserIdA { get; set; }
        public Nullable<int> UserIdD { get; set; }
        public Nullable<int> UserIdCpa { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
        public virtual GroupInfo GroupInfo { get; set; }
        public virtual ICollection<Role> Roles { get; set; }
        public virtual User AnalysContact { get; set; }
        public virtual User LevInfoContact { get; set; }
        public virtual User WebstyrningContact { get; set; }
        public virtual User ChangedByUser { get; set; }
        public virtual ICollection<AdvanceExtension> AdvanceExtensions { get; set; }
    }
}
