//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telia.NTW.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meddelandes
    {
        public Meddelandes()
        {
            this.RolesForMessage = new HashSet<RolesForMessage>();
        }
    
        public int Id { get; set; }
        public int Type { get; set; }
        public System.DateTime From { get; set; }
        public System.DateTime To { get; set; }
        public string Text { get; set; }
    
        public virtual ICollection<RolesForMessage> RolesForMessage { get; set; }
    }
}
