//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telia.NTW.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessTable
    {
        public int ProcessID { get; set; }
        public string ProcessName { get; set; }
        public string ProcessType { get; set; }
        public Nullable<int> NoOfExec { get; set; }
        public Nullable<short> DeleteLimit { get; set; }
    }
}
