//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telia.NTW.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessHeader
    {
        public int ProcessID { get; set; }
        public int PID { get; set; }
        public bool Success { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string ProcessOwner { get; set; }
        public string Note { get; set; }
    }
}
