//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telia.NTW.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolesForMessage
    {
        public int Id { get; set; }
        public int MessageId { get; set; }
        public int RoleId { get; set; }
    
        public virtual Meddelandes Meddelandes { get; set; }
        public virtual Role Role { get; set; }
    }
}
