//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telia.NTW.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.Companies = new HashSet<CompanyInfo>();
            this.Users = new HashSet<User>();
            this.IncludedRoles = new HashSet<Role>();
            this.IncludedByRoles = new HashSet<Role>();
            this.RolesForMessage = new HashSet<RolesForMessage>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<bool> ApplicationRole { get; set; }
    
        public virtual ICollection<CompanyInfo> Companies { get; set; }
        public virtual ICollection<User> Users { get; set; }
        public virtual ICollection<Role> IncludedRoles { get; set; }
        public virtual ICollection<Role> IncludedByRoles { get; set; }
        public virtual ICollection<RolesForMessage> RolesForMessage { get; set; }
    }
}
