//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telia.NTW.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceLog
    {
        public int Id { get; set; }
        public string Component { get; set; }
        public string InternalFunction { get; set; }
        public string ErrNo { get; set; }
        public string ErrNoHex { get; set; }
        public string Description { get; set; }
        public string DetailDescription { get; set; }
        public Nullable<short> Severity { get; set; }
        public System.DateTime TimeStamp { get; set; }
    }
}
