//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telia.NTW.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAdvanceNumbers
    {
        public int UserID { get; set; }
        public int AdvanceExtId { get; set; }
        public short AnalysisView { get; set; }
        public bool AnalysisRawData { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> ChangedDate { get; set; }
        public Nullable<int> ChangedBy { get; set; }
    
        public virtual AdvanceExtension AdvanceExtension { get; set; }
        public virtual User User { get; set; }
        public virtual User ChangedByUser { get; set; }
    }
}
