//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telia.NTW.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSettings
    {
        public short NoOfRecords { get; set; }
        public bool Expmenu { get; set; }
        public string Language { get; set; }
        public Nullable<System.DateTime> LogonDate { get; set; }
        public int UserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
