//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telia.NTW.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Roles = new HashSet<Role>();
            this.ChangedCompanyInfos = new HashSet<CompanyInfo>();
            this.ChangedUsers = new HashSet<User>();
            this.UserAdvanceNumbers = new HashSet<UserAdvanceNumbers>();
            this.ChangedAdvanceExtensions = new HashSet<AdvanceExtension>();
            this.ChangedUserAdvanceNumbers = new HashSet<UserAdvanceNumbers>();
            this.ChangedGroupInfos = new HashSet<GroupInfo>();
        }
    
        public int UserID { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string LoginName { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public string Note { get; set; }
        public string Security { get; set; }
        public string CustNo { get; set; }
        public bool Parent { get; set; }
        public string Email { get; set; }
        public string TelNo { get; set; }
        public string Eno { get; set; }
        public string SalesUnitsAllowed { get; set; }
        public string ProdStod { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> ChangedDate { get; set; }
        public Nullable<int> ChangedBy { get; set; }
        public Nullable<System.DateTime> LogonDate { get; set; }
    
        public virtual CompanyInfo Company { get; set; }
        public virtual ICollection<Role> Roles { get; set; }
        public virtual ICollection<CompanyInfo> ChangedCompanyInfos { get; set; }
        public virtual ICollection<User> ChangedUsers { get; set; }
        public virtual User ChangedByUser { get; set; }
        public virtual ICollection<UserAdvanceNumbers> UserAdvanceNumbers { get; set; }
        public virtual ICollection<AdvanceExtension> ChangedAdvanceExtensions { get; set; }
        public virtual ICollection<UserAdvanceNumbers> ChangedUserAdvanceNumbers { get; set; }
        public virtual ICollection<GroupInfo> ChangedGroupInfos { get; set; }
    }
}
