// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
#pragma warning disable 1591, 3008, 3009
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Telia.NTW.Web.Controllers
{
    public partial class AdminController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected AdminController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Hantera()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Hantera);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual Sigma.Utils.ActionResults.ExcelActionResult Hantera_ExportToExcel()
        {
            return new T4MVC_Sigma_Utils_ActionResults_ExcelActionResult(Area, Name, ActionNames.Hantera_ExportToExcel);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Hantera_Användare_Edit()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Hantera_Användare_Edit);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Hantera_User_Delete()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Hantera_User_Delete);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Get_OrgNr()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Get_OrgNr);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Hantera_Bolag_Edit()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Hantera_Bolag_Edit);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult Hantera_Bolag_Contact()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.Hantera_Bolag_Contact);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Hantera_Bolag_Nummer_Edit()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Hantera_Bolag_Nummer_Edit);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult Hantera_Bolag_Nummer_Edit_Data()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.Hantera_Bolag_Nummer_Edit_Data);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Hantera_Bolag_Nummer_Add()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Hantera_Bolag_Nummer_Add);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Hantera_Bolag_Nummer_Delete()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Hantera_Bolag_Nummer_Delete);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Hantera_Bolag_Delete()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Hantera_Bolag_Delete);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Hantera_Bolag_LoggaIn()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Hantera_Bolag_LoggaIn);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Hantera_Koncern_Edit()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Hantera_Koncern_Edit);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Hantera_Koncern_Delete()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Hantera_Koncern_Delete);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult RedigeraMeddelande()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RedigeraMeddelande);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult TaBortMeddelande()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.TaBortMeddelande);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public AdminController Actions { get { return MVC.Admin; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Admin";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Admin";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string InvalidAntiForgeryToken = "InvalidAntiForgeryToken";
            public readonly string Hantera = "Hantera";
            public readonly string Hantera_ExportToExcel = "Hantera_ExportToExcel";
            public readonly string Hantera_Användare_Create = "Hantera_Användare_Create";
            public readonly string Hantera_Användare_Edit = "Hantera_Användare_Edit";
            public readonly string Hantera_User_Delete = "Hantera_User_Delete";
            public readonly string Get_OrgNr = "Get_OrgNr";
            public readonly string Hantera_Bolag_Create = "Hantera_Bolag_Create";
            public readonly string Hantera_Bolag_Edit = "Hantera_Bolag_Edit";
            public readonly string Hantera_Bolag_Contact = "Hantera_Bolag_Contact";
            public readonly string Hantera_Bolag_Nummer_Edit = "Hantera_Bolag_Nummer_Edit";
            public readonly string Hantera_Bolag_Nummer_Edit_Data = "Hantera_Bolag_Nummer_Edit_Data";
            public readonly string Hantera_Bolag_Nummer_Add = "Hantera_Bolag_Nummer_Add";
            public readonly string Hantera_Bolag_Nummer_Delete = "Hantera_Bolag_Nummer_Delete";
            public readonly string Hantera_Bolag_Delete = "Hantera_Bolag_Delete";
            public readonly string Hantera_Bolag_Inloggning = "Hantera_Bolag_Inloggning";
            public readonly string Hantera_Bolag_LoggaIn = "Hantera_Bolag_LoggaIn";
            public readonly string Hantera_Koncern_Create = "Hantera_Koncern_Create";
            public readonly string Hantera_Koncern_Edit = "Hantera_Koncern_Edit";
            public readonly string Hantera_Koncern_Delete = "Hantera_Koncern_Delete";
            public readonly string Meddelande = "Meddelande";
            public readonly string SkapaMeddelande = "SkapaMeddelande";
            public readonly string RedigeraMeddelande = "RedigeraMeddelande";
            public readonly string TaBortMeddelande = "TaBortMeddelande";
            public readonly string Användarstatistik = "Användarstatistik";
            public readonly string Loggar = "Loggar";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string InvalidAntiForgeryToken = "InvalidAntiForgeryToken";
            public const string Hantera = "Hantera";
            public const string Hantera_ExportToExcel = "Hantera_ExportToExcel";
            public const string Hantera_Användare_Create = "Hantera_Användare_Create";
            public const string Hantera_Användare_Edit = "Hantera_Användare_Edit";
            public const string Hantera_User_Delete = "Hantera_User_Delete";
            public const string Get_OrgNr = "Get_OrgNr";
            public const string Hantera_Bolag_Create = "Hantera_Bolag_Create";
            public const string Hantera_Bolag_Edit = "Hantera_Bolag_Edit";
            public const string Hantera_Bolag_Contact = "Hantera_Bolag_Contact";
            public const string Hantera_Bolag_Nummer_Edit = "Hantera_Bolag_Nummer_Edit";
            public const string Hantera_Bolag_Nummer_Edit_Data = "Hantera_Bolag_Nummer_Edit_Data";
            public const string Hantera_Bolag_Nummer_Add = "Hantera_Bolag_Nummer_Add";
            public const string Hantera_Bolag_Nummer_Delete = "Hantera_Bolag_Nummer_Delete";
            public const string Hantera_Bolag_Delete = "Hantera_Bolag_Delete";
            public const string Hantera_Bolag_Inloggning = "Hantera_Bolag_Inloggning";
            public const string Hantera_Bolag_LoggaIn = "Hantera_Bolag_LoggaIn";
            public const string Hantera_Koncern_Create = "Hantera_Koncern_Create";
            public const string Hantera_Koncern_Edit = "Hantera_Koncern_Edit";
            public const string Hantera_Koncern_Delete = "Hantera_Koncern_Delete";
            public const string Meddelande = "Meddelande";
            public const string SkapaMeddelande = "SkapaMeddelande";
            public const string RedigeraMeddelande = "RedigeraMeddelande";
            public const string TaBortMeddelande = "TaBortMeddelande";
            public const string Användarstatistik = "Användarstatistik";
            public const string Loggar = "Loggar";
        }


        static readonly ActionParamsClass_Hantera s_params_Hantera = new ActionParamsClass_Hantera();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Hantera HanteraParams { get { return s_params_Hantera; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Hantera
        {
            public readonly string errorMessages = "errorMessages";
            public readonly string search = "search";
        }
        static readonly ActionParamsClass_Hantera_ExportToExcel s_params_Hantera_ExportToExcel = new ActionParamsClass_Hantera_ExportToExcel();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Hantera_ExportToExcel Hantera_ExportToExcelParams { get { return s_params_Hantera_ExportToExcel; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Hantera_ExportToExcel
        {
            public readonly string search = "search";
        }
        static readonly ActionParamsClass_Hantera_Användare_Create s_params_Hantera_Användare_Create = new ActionParamsClass_Hantera_Användare_Create();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Hantera_Användare_Create Hantera_Användare_CreateParams { get { return s_params_Hantera_Användare_Create; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Hantera_Användare_Create
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_Hantera_Användare_Edit s_params_Hantera_Användare_Edit = new ActionParamsClass_Hantera_Användare_Edit();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Hantera_Användare_Edit Hantera_Användare_EditParams { get { return s_params_Hantera_Användare_Edit; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Hantera_Användare_Edit
        {
            public readonly string userId = "userId";
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_Hantera_User_Delete s_params_Hantera_User_Delete = new ActionParamsClass_Hantera_User_Delete();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Hantera_User_Delete Hantera_User_DeleteParams { get { return s_params_Hantera_User_Delete; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Hantera_User_Delete
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_Get_OrgNr s_params_Get_OrgNr = new ActionParamsClass_Get_OrgNr();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Get_OrgNr Get_OrgNrParams { get { return s_params_Get_OrgNr; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Get_OrgNr
        {
            public readonly string orgNrId = "orgNrId";
        }
        static readonly ActionParamsClass_Hantera_Bolag_Create s_params_Hantera_Bolag_Create = new ActionParamsClass_Hantera_Bolag_Create();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Hantera_Bolag_Create Hantera_Bolag_CreateParams { get { return s_params_Hantera_Bolag_Create; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Hantera_Bolag_Create
        {
            public readonly string bolagEditViewModel = "bolagEditViewModel";
        }
        static readonly ActionParamsClass_Hantera_Bolag_Edit s_params_Hantera_Bolag_Edit = new ActionParamsClass_Hantera_Bolag_Edit();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Hantera_Bolag_Edit Hantera_Bolag_EditParams { get { return s_params_Hantera_Bolag_Edit; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Hantera_Bolag_Edit
        {
            public readonly string companyId = "companyId";
            public readonly string bolagEditViewModel = "bolagEditViewModel";
        }
        static readonly ActionParamsClass_Hantera_Bolag_Contact s_params_Hantera_Bolag_Contact = new ActionParamsClass_Hantera_Bolag_Contact();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Hantera_Bolag_Contact Hantera_Bolag_ContactParams { get { return s_params_Hantera_Bolag_Contact; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Hantera_Bolag_Contact
        {
            public readonly string userId = "userId";
        }
        static readonly ActionParamsClass_Hantera_Bolag_Nummer_Edit s_params_Hantera_Bolag_Nummer_Edit = new ActionParamsClass_Hantera_Bolag_Nummer_Edit();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Hantera_Bolag_Nummer_Edit Hantera_Bolag_Nummer_EditParams { get { return s_params_Hantera_Bolag_Nummer_Edit; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Hantera_Bolag_Nummer_Edit
        {
            public readonly string advanceExtId = "advanceExtId";
            public readonly string companyId = "companyId";
            public readonly string bolagsnamn = "bolagsnamn";
        }
        static readonly ActionParamsClass_Hantera_Bolag_Nummer_Edit_Data s_params_Hantera_Bolag_Nummer_Edit_Data = new ActionParamsClass_Hantera_Bolag_Nummer_Edit_Data();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Hantera_Bolag_Nummer_Edit_Data Hantera_Bolag_Nummer_Edit_DataParams { get { return s_params_Hantera_Bolag_Nummer_Edit_Data; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Hantera_Bolag_Nummer_Edit_Data
        {
            public readonly string advanceExtId = "advanceExtId";
            public readonly string nummerEditModel = "nummerEditModel";
        }
        static readonly ActionParamsClass_Hantera_Bolag_Nummer_Add s_params_Hantera_Bolag_Nummer_Add = new ActionParamsClass_Hantera_Bolag_Nummer_Add();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Hantera_Bolag_Nummer_Add Hantera_Bolag_Nummer_AddParams { get { return s_params_Hantera_Bolag_Nummer_Add; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Hantera_Bolag_Nummer_Add
        {
            public readonly string companyId = "companyId";
            public readonly string bolagsnamn = "bolagsnamn";
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_Hantera_Bolag_Nummer_Delete s_params_Hantera_Bolag_Nummer_Delete = new ActionParamsClass_Hantera_Bolag_Nummer_Delete();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Hantera_Bolag_Nummer_Delete Hantera_Bolag_Nummer_DeleteParams { get { return s_params_Hantera_Bolag_Nummer_Delete; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Hantera_Bolag_Nummer_Delete
        {
            public readonly string id = "id";
            public readonly string id2 = "id2";
        }
        static readonly ActionParamsClass_Hantera_Bolag_Delete s_params_Hantera_Bolag_Delete = new ActionParamsClass_Hantera_Bolag_Delete();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Hantera_Bolag_Delete Hantera_Bolag_DeleteParams { get { return s_params_Hantera_Bolag_Delete; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Hantera_Bolag_Delete
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_Hantera_Bolag_Inloggning s_params_Hantera_Bolag_Inloggning = new ActionParamsClass_Hantera_Bolag_Inloggning();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Hantera_Bolag_Inloggning Hantera_Bolag_InloggningParams { get { return s_params_Hantera_Bolag_Inloggning; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Hantera_Bolag_Inloggning
        {
            public readonly string search = "search";
        }
        static readonly ActionParamsClass_Hantera_Bolag_LoggaIn s_params_Hantera_Bolag_LoggaIn = new ActionParamsClass_Hantera_Bolag_LoggaIn();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Hantera_Bolag_LoggaIn Hantera_Bolag_LoggaInParams { get { return s_params_Hantera_Bolag_LoggaIn; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Hantera_Bolag_LoggaIn
        {
            public readonly string companyId = "companyId";
        }
        static readonly ActionParamsClass_Hantera_Koncern_Create s_params_Hantera_Koncern_Create = new ActionParamsClass_Hantera_Koncern_Create();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Hantera_Koncern_Create Hantera_Koncern_CreateParams { get { return s_params_Hantera_Koncern_Create; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Hantera_Koncern_Create
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_Hantera_Koncern_Edit s_params_Hantera_Koncern_Edit = new ActionParamsClass_Hantera_Koncern_Edit();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Hantera_Koncern_Edit Hantera_Koncern_EditParams { get { return s_params_Hantera_Koncern_Edit; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Hantera_Koncern_Edit
        {
            public readonly string groupId = "groupId";
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_Hantera_Koncern_Delete s_params_Hantera_Koncern_Delete = new ActionParamsClass_Hantera_Koncern_Delete();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Hantera_Koncern_Delete Hantera_Koncern_DeleteParams { get { return s_params_Hantera_Koncern_Delete; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Hantera_Koncern_Delete
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_SkapaMeddelande s_params_SkapaMeddelande = new ActionParamsClass_SkapaMeddelande();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SkapaMeddelande SkapaMeddelandeParams { get { return s_params_SkapaMeddelande; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SkapaMeddelande
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_RedigeraMeddelande s_params_RedigeraMeddelande = new ActionParamsClass_RedigeraMeddelande();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_RedigeraMeddelande RedigeraMeddelandeParams { get { return s_params_RedigeraMeddelande; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_RedigeraMeddelande
        {
            public readonly string id = "id";
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_TaBortMeddelande s_params_TaBortMeddelande = new ActionParamsClass_TaBortMeddelande();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_TaBortMeddelande TaBortMeddelandeParams { get { return s_params_TaBortMeddelande; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_TaBortMeddelande
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_Loggar s_params_Loggar = new ActionParamsClass_Loggar();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Loggar LoggarParams { get { return s_params_Loggar; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Loggar
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _Hantera_Användare_List = "_Hantera_Användare_List";
                public readonly string _Hantera_Bolag_EditForm = "_Hantera_Bolag_EditForm";
                public readonly string _Hantera_Bolag_List = "_Hantera_Bolag_List";
                public readonly string _Hantera_Bolag_Nummer_List = "_Hantera_Bolag_Nummer_List";
                public readonly string _Hantera_Koncern_EditForm = "_Hantera_Koncern_EditForm";
                public readonly string _Hantera_Koncern_List = "_Hantera_Koncern_List";
                public readonly string _HanteraAnvändare = "_HanteraAnvändare";
                public readonly string _MeddelandeField = "_MeddelandeField";
                public readonly string AnvändarStatistik = "AnvändarStatistik";
                public readonly string Hantera = "Hantera";
                public readonly string Hantera_Användare_Create = "Hantera_Användare_Create";
                public readonly string Hantera_Användare_Edit = "Hantera_Användare_Edit";
                public readonly string Hantera_Bolag_Create = "Hantera_Bolag_Create";
                public readonly string Hantera_Bolag_Edit = "Hantera_Bolag_Edit";
                public readonly string Hantera_Bolag_Inloggning = "Hantera_Bolag_Inloggning";
                public readonly string Hantera_Bolag_Nummer_Add = "Hantera_Bolag_Nummer_Add";
                public readonly string Hantera_Bolag_Nummer_Edit = "Hantera_Bolag_Nummer_Edit";
                public readonly string Hantera_Koncern_Create = "Hantera_Koncern_Create";
                public readonly string Hantera_Koncern_Edit = "Hantera_Koncern_Edit";
                public readonly string Loggar = "Loggar";
                public readonly string Meddelande = "Meddelande";
                public readonly string RedigeraMeddelande = "RedigeraMeddelande";
                public readonly string SkapaMeddelande = "SkapaMeddelande";
            }
            public readonly string _Hantera_Användare_List = "~/Views/Admin/_Hantera_Användare_List.cshtml";
            public readonly string _Hantera_Bolag_EditForm = "~/Views/Admin/_Hantera_Bolag_EditForm.cshtml";
            public readonly string _Hantera_Bolag_List = "~/Views/Admin/_Hantera_Bolag_List.cshtml";
            public readonly string _Hantera_Bolag_Nummer_List = "~/Views/Admin/_Hantera_Bolag_Nummer_List.cshtml";
            public readonly string _Hantera_Koncern_EditForm = "~/Views/Admin/_Hantera_Koncern_EditForm.cshtml";
            public readonly string _Hantera_Koncern_List = "~/Views/Admin/_Hantera_Koncern_List.cshtml";
            public readonly string _HanteraAnvändare = "~/Views/Admin/_HanteraAnvändare.cshtml";
            public readonly string _MeddelandeField = "~/Views/Admin/_MeddelandeField.cshtml";
            public readonly string AnvändarStatistik = "~/Views/Admin/AnvändarStatistik.cshtml";
            public readonly string Hantera = "~/Views/Admin/Hantera.cshtml";
            public readonly string Hantera_Användare_Create = "~/Views/Admin/Hantera_Användare_Create.cshtml";
            public readonly string Hantera_Användare_Edit = "~/Views/Admin/Hantera_Användare_Edit.cshtml";
            public readonly string Hantera_Bolag_Create = "~/Views/Admin/Hantera_Bolag_Create.cshtml";
            public readonly string Hantera_Bolag_Edit = "~/Views/Admin/Hantera_Bolag_Edit.cshtml";
            public readonly string Hantera_Bolag_Inloggning = "~/Views/Admin/Hantera_Bolag_Inloggning.cshtml";
            public readonly string Hantera_Bolag_Nummer_Add = "~/Views/Admin/Hantera_Bolag_Nummer_Add.cshtml";
            public readonly string Hantera_Bolag_Nummer_Edit = "~/Views/Admin/Hantera_Bolag_Nummer_Edit.cshtml";
            public readonly string Hantera_Koncern_Create = "~/Views/Admin/Hantera_Koncern_Create.cshtml";
            public readonly string Hantera_Koncern_Edit = "~/Views/Admin/Hantera_Koncern_Edit.cshtml";
            public readonly string Loggar = "~/Views/Admin/Loggar.cshtml";
            public readonly string Meddelande = "~/Views/Admin/Meddelande.cshtml";
            public readonly string RedigeraMeddelande = "~/Views/Admin/RedigeraMeddelande.cshtml";
            public readonly string SkapaMeddelande = "~/Views/Admin/SkapaMeddelande.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_AdminController : Telia.NTW.Web.Controllers.AdminController
    {
        public T4MVC_AdminController() : base(Dummy.Instance) { }

        [NonAction]
        partial void InvalidAntiForgeryTokenOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult InvalidAntiForgeryToken()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.InvalidAntiForgeryToken);
            InvalidAntiForgeryTokenOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void HanteraOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.Collections.Generic.List<string> errorMessages);

        [NonAction]
        public override System.Web.Mvc.ActionResult Hantera(System.Collections.Generic.List<string> errorMessages)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Hantera);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "errorMessages", errorMessages);
            HanteraOverride(callInfo, errorMessages);
            return callInfo;
        }

        [NonAction]
        partial void HanteraOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string search, System.Collections.Generic.List<string> errorMessages);

        [NonAction]
        public override System.Web.Mvc.ActionResult Hantera(string search, System.Collections.Generic.List<string> errorMessages)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Hantera);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "search", search);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "errorMessages", errorMessages);
            HanteraOverride(callInfo, search, errorMessages);
            return callInfo;
        }

        [NonAction]
        partial void Hantera_ExportToExcelOverride(T4MVC_Sigma_Utils_ActionResults_ExcelActionResult callInfo, string search);

        [NonAction]
        public override Sigma.Utils.ActionResults.ExcelActionResult Hantera_ExportToExcel(string search)
        {
            var callInfo = new T4MVC_Sigma_Utils_ActionResults_ExcelActionResult(Area, Name, ActionNames.Hantera_ExportToExcel);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "search", search);
            Hantera_ExportToExcelOverride(callInfo, search);
            return callInfo;
        }

        [NonAction]
        partial void Hantera_Användare_CreateOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Hantera_Användare_Create()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Hantera_Användare_Create);
            Hantera_Användare_CreateOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void Hantera_Användare_CreateOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Telia.NTW.Web.ViewModel.Admin.Hantera.RedigeraAnvändareViewModel viewModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult Hantera_Användare_Create(Telia.NTW.Web.ViewModel.Admin.Hantera.RedigeraAnvändareViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Hantera_Användare_Create);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            Hantera_Användare_CreateOverride(callInfo, viewModel);
            return callInfo;
        }

        [NonAction]
        partial void Hantera_Användare_EditOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int userId);

        [NonAction]
        public override System.Web.Mvc.ActionResult Hantera_Användare_Edit(int userId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Hantera_Användare_Edit);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "userId", userId);
            Hantera_Användare_EditOverride(callInfo, userId);
            return callInfo;
        }

        [NonAction]
        partial void Hantera_Användare_EditOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Telia.NTW.Web.ViewModel.Admin.Hantera.RedigeraAnvändareViewModel viewModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult Hantera_Användare_Edit(Telia.NTW.Web.ViewModel.Admin.Hantera.RedigeraAnvändareViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Hantera_Användare_Edit);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            Hantera_Användare_EditOverride(callInfo, viewModel);
            return callInfo;
        }

        [NonAction]
        partial void Hantera_User_DeleteOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult Hantera_User_Delete(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Hantera_User_Delete);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            Hantera_User_DeleteOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void Get_OrgNrOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string orgNrId);

        [NonAction]
        public override System.Web.Mvc.ActionResult Get_OrgNr(string orgNrId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Get_OrgNr);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "orgNrId", orgNrId);
            Get_OrgNrOverride(callInfo, orgNrId);
            return callInfo;
        }

        [NonAction]
        partial void Hantera_Bolag_CreateOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Hantera_Bolag_Create()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Hantera_Bolag_Create);
            Hantera_Bolag_CreateOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void Hantera_Bolag_CreateOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Telia.NTW.Web.ViewModel.Admin.Hantera.BolagEditViewModel bolagEditViewModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult Hantera_Bolag_Create(Telia.NTW.Web.ViewModel.Admin.Hantera.BolagEditViewModel bolagEditViewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Hantera_Bolag_Create);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "bolagEditViewModel", bolagEditViewModel);
            Hantera_Bolag_CreateOverride(callInfo, bolagEditViewModel);
            return callInfo;
        }

        [NonAction]
        partial void Hantera_Bolag_EditOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int companyId);

        [NonAction]
        public override System.Web.Mvc.ActionResult Hantera_Bolag_Edit(int companyId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Hantera_Bolag_Edit);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "companyId", companyId);
            Hantera_Bolag_EditOverride(callInfo, companyId);
            return callInfo;
        }

        [NonAction]
        partial void Hantera_Bolag_EditOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Telia.NTW.Web.ViewModel.Admin.Hantera.BolagEditViewModel bolagEditViewModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult Hantera_Bolag_Edit(Telia.NTW.Web.ViewModel.Admin.Hantera.BolagEditViewModel bolagEditViewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Hantera_Bolag_Edit);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "bolagEditViewModel", bolagEditViewModel);
            Hantera_Bolag_EditOverride(callInfo, bolagEditViewModel);
            return callInfo;
        }

        [NonAction]
        partial void Hantera_Bolag_ContactOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, int? userId);

        [NonAction]
        public override System.Web.Mvc.JsonResult Hantera_Bolag_Contact(int? userId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.Hantera_Bolag_Contact);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "userId", userId);
            Hantera_Bolag_ContactOverride(callInfo, userId);
            return callInfo;
        }

        [NonAction]
        partial void Hantera_Bolag_Nummer_EditOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int advanceExtId, int companyId, string bolagsnamn);

        [NonAction]
        public override System.Web.Mvc.ActionResult Hantera_Bolag_Nummer_Edit(int advanceExtId, int companyId, string bolagsnamn)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Hantera_Bolag_Nummer_Edit);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "advanceExtId", advanceExtId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "companyId", companyId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "bolagsnamn", bolagsnamn);
            Hantera_Bolag_Nummer_EditOverride(callInfo, advanceExtId, companyId, bolagsnamn);
            return callInfo;
        }

        [NonAction]
        partial void Hantera_Bolag_Nummer_Edit_DataOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, int advanceExtId);

        [NonAction]
        public override System.Web.Mvc.JsonResult Hantera_Bolag_Nummer_Edit_Data(int advanceExtId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.Hantera_Bolag_Nummer_Edit_Data);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "advanceExtId", advanceExtId);
            Hantera_Bolag_Nummer_Edit_DataOverride(callInfo, advanceExtId);
            return callInfo;
        }

        [NonAction]
        partial void Hantera_Bolag_Nummer_Edit_DataOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, Telia.NTW.Web.ViewModel.Admin.Hantera.NummerEditModel nummerEditModel);

        [NonAction]
        public override System.Web.Mvc.JsonResult Hantera_Bolag_Nummer_Edit_Data(Telia.NTW.Web.ViewModel.Admin.Hantera.NummerEditModel nummerEditModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.Hantera_Bolag_Nummer_Edit_Data);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "nummerEditModel", nummerEditModel);
            Hantera_Bolag_Nummer_Edit_DataOverride(callInfo, nummerEditModel);
            return callInfo;
        }

        [NonAction]
        partial void Hantera_Bolag_Nummer_AddOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int companyId, string bolagsnamn);

        [NonAction]
        public override System.Web.Mvc.ActionResult Hantera_Bolag_Nummer_Add(int companyId, string bolagsnamn)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Hantera_Bolag_Nummer_Add);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "companyId", companyId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "bolagsnamn", bolagsnamn);
            Hantera_Bolag_Nummer_AddOverride(callInfo, companyId, bolagsnamn);
            return callInfo;
        }

        [NonAction]
        partial void Hantera_Bolag_Nummer_AddOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Telia.NTW.Web.ViewModel.Admin.Hantera.BolagNummerAddViewModel viewModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult Hantera_Bolag_Nummer_Add(Telia.NTW.Web.ViewModel.Admin.Hantera.BolagNummerAddViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Hantera_Bolag_Nummer_Add);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            Hantera_Bolag_Nummer_AddOverride(callInfo, viewModel);
            return callInfo;
        }

        [NonAction]
        partial void Hantera_Bolag_Nummer_DeleteOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id, int id2);

        [NonAction]
        public override System.Web.Mvc.ActionResult Hantera_Bolag_Nummer_Delete(int id, int id2)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Hantera_Bolag_Nummer_Delete);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id2", id2);
            Hantera_Bolag_Nummer_DeleteOverride(callInfo, id, id2);
            return callInfo;
        }

        [NonAction]
        partial void Hantera_Bolag_DeleteOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult Hantera_Bolag_Delete(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Hantera_Bolag_Delete);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            Hantera_Bolag_DeleteOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void Hantera_Bolag_InloggningOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Hantera_Bolag_Inloggning()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Hantera_Bolag_Inloggning);
            Hantera_Bolag_InloggningOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void Hantera_Bolag_InloggningOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string search);

        [NonAction]
        public override System.Web.Mvc.ActionResult Hantera_Bolag_Inloggning(string search)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Hantera_Bolag_Inloggning);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "search", search);
            Hantera_Bolag_InloggningOverride(callInfo, search);
            return callInfo;
        }

        [NonAction]
        partial void Hantera_Bolag_LoggaInOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int companyId);

        [NonAction]
        public override System.Web.Mvc.ActionResult Hantera_Bolag_LoggaIn(int companyId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Hantera_Bolag_LoggaIn);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "companyId", companyId);
            Hantera_Bolag_LoggaInOverride(callInfo, companyId);
            return callInfo;
        }

        [NonAction]
        partial void Hantera_Koncern_CreateOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Hantera_Koncern_Create()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Hantera_Koncern_Create);
            Hantera_Koncern_CreateOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void Hantera_Koncern_CreateOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Telia.NTW.Web.ViewModel.Admin.Hantera.Koncern viewModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult Hantera_Koncern_Create(Telia.NTW.Web.ViewModel.Admin.Hantera.Koncern viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Hantera_Koncern_Create);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            Hantera_Koncern_CreateOverride(callInfo, viewModel);
            return callInfo;
        }

        [NonAction]
        partial void Hantera_Koncern_EditOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int groupId);

        [NonAction]
        public override System.Web.Mvc.ActionResult Hantera_Koncern_Edit(int groupId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Hantera_Koncern_Edit);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "groupId", groupId);
            Hantera_Koncern_EditOverride(callInfo, groupId);
            return callInfo;
        }

        [NonAction]
        partial void Hantera_Koncern_EditOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Telia.NTW.Web.ViewModel.Admin.Hantera.Koncern viewModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult Hantera_Koncern_Edit(Telia.NTW.Web.ViewModel.Admin.Hantera.Koncern viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Hantera_Koncern_Edit);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            Hantera_Koncern_EditOverride(callInfo, viewModel);
            return callInfo;
        }

        [NonAction]
        partial void Hantera_Koncern_DeleteOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult Hantera_Koncern_Delete(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Hantera_Koncern_Delete);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            Hantera_Koncern_DeleteOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void MeddelandeOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Meddelande()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Meddelande);
            MeddelandeOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void SkapaMeddelandeOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult SkapaMeddelande()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SkapaMeddelande);
            SkapaMeddelandeOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void SkapaMeddelandeOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Telia.NTW.Web.ViewModel.Admin.Meddelanden.MeddelandeViewModel viewModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult SkapaMeddelande(Telia.NTW.Web.ViewModel.Admin.Meddelanden.MeddelandeViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SkapaMeddelande);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            SkapaMeddelandeOverride(callInfo, viewModel);
            return callInfo;
        }

        [NonAction]
        partial void RedigeraMeddelandeOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult RedigeraMeddelande(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RedigeraMeddelande);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            RedigeraMeddelandeOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void RedigeraMeddelandeOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Telia.NTW.Web.ViewModel.Admin.Meddelanden.MeddelandeViewModel viewModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult RedigeraMeddelande(Telia.NTW.Web.ViewModel.Admin.Meddelanden.MeddelandeViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RedigeraMeddelande);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            RedigeraMeddelandeOverride(callInfo, viewModel);
            return callInfo;
        }

        [NonAction]
        partial void TaBortMeddelandeOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult TaBortMeddelande(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.TaBortMeddelande);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            TaBortMeddelandeOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void AnvändarstatistikOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Användarstatistik()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Användarstatistik);
            AnvändarstatistikOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void LoggarOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Loggar()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Loggar);
            LoggarOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void LoggarOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Telia.NTW.Web.ViewModel.Admin.Loggar.LoggarViewModel viewModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult Loggar(Telia.NTW.Web.ViewModel.Admin.Loggar.LoggarViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Loggar);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            LoggarOverride(callInfo, viewModel);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009
