// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
#pragma warning disable 1591, 3008, 3009
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Telia.NTW.Web.Controllers
{
    public partial class AnalysController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected AnalysController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Export()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Export);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SvarstallenAndUpptagningsomraden()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SvarstallenAndUpptagningsomraden);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ExportExcel()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ExportExcel);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public AnalysController Actions { get { return MVC.Analys; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Analys";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Analys";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string Export = "Index";
            public readonly string SvarstallenAndUpptagningsomraden = "SvarstallenAndUpptagningsomraden";
            public readonly string ExportExcel = "Index";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string Export = "Index";
            public const string SvarstallenAndUpptagningsomraden = "SvarstallenAndUpptagningsomraden";
            public const string ExportExcel = "Index";
        }


        static readonly ActionParamsClass_Index s_params_Index = new ActionParamsClass_Index();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Index IndexParams { get { return s_params_Index; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Index
        {
            public readonly string filterViewModel = "filterViewModel";
        }
        static readonly ActionParamsClass_Export s_params_Export = new ActionParamsClass_Export();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Export ExportParams { get { return s_params_Export; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Export
        {
            public readonly string filterViewModel = "filterViewModel";
        }
        static readonly ActionParamsClass_SvarstallenAndUpptagningsomraden s_params_SvarstallenAndUpptagningsomraden = new ActionParamsClass_SvarstallenAndUpptagningsomraden();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SvarstallenAndUpptagningsomraden SvarstallenAndUpptagningsomradenParams { get { return s_params_SvarstallenAndUpptagningsomraden; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SvarstallenAndUpptagningsomraden
        {
            public readonly string id = "id";
            public readonly string frånDatum = "frånDatum";
            public readonly string tillDatum = "tillDatum";
        }
        static readonly ActionParamsClass_ExportExcel s_params_ExportExcel = new ActionParamsClass_ExportExcel();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ExportExcel ExportExcelParams { get { return s_params_ExportExcel; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ExportExcel
        {
            public readonly string filterViewModel = "filterViewModel";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _Data = "_Data";
                public readonly string _Filter = "_Filter";
                public readonly string _Svarstallen_Upptagningsomraden = "_Svarstallen_Upptagningsomraden";
                public readonly string Index = "Index";
            }
            public readonly string _Data = "~/Views/Analys/_Data.cshtml";
            public readonly string _Filter = "~/Views/Analys/_Filter.cshtml";
            public readonly string _Svarstallen_Upptagningsomraden = "~/Views/Analys/_Svarstallen_Upptagningsomraden.cshtml";
            public readonly string Index = "~/Views/Analys/Index.cshtml";
            static readonly _EditorTemplatesClass s_EditorTemplates = new _EditorTemplatesClass();
            public _EditorTemplatesClass EditorTemplates { get { return s_EditorTemplates; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _EditorTemplatesClass
            {
                public readonly string FilterTyp = "FilterTyp";
                public readonly string Svarstallen = "Svarstallen";
                public readonly string Upptagningsomraden = "Upptagningsomraden";
            }
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_AnalysController : Telia.NTW.Web.Controllers.AnalysController
    {
        public T4MVC_AnalysController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Telia.NTW.Web.ViewModel.Analys.AnalysFilterViewModel filterViewModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index(Telia.NTW.Web.ViewModel.Analys.AnalysFilterViewModel filterViewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "filterViewModel", filterViewModel);
            IndexOverride(callInfo, filterViewModel);
            return callInfo;
        }

        [NonAction]
        partial void ExportOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Telia.NTW.Web.ViewModel.Analys.AnalysFilterViewModel filterViewModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult Export(Telia.NTW.Web.ViewModel.Analys.AnalysFilterViewModel filterViewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Export);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "filterViewModel", filterViewModel);
            ExportOverride(callInfo, filterViewModel);
            return callInfo;
        }

        [NonAction]
        partial void SvarstallenAndUpptagningsomradenOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id, System.DateTime? frånDatum, System.DateTime? tillDatum);

        [NonAction]
        public override System.Web.Mvc.ActionResult SvarstallenAndUpptagningsomraden(int id, System.DateTime? frånDatum, System.DateTime? tillDatum)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SvarstallenAndUpptagningsomraden);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "frånDatum", frånDatum);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "tillDatum", tillDatum);
            SvarstallenAndUpptagningsomradenOverride(callInfo, id, frånDatum, tillDatum);
            return callInfo;
        }

        [NonAction]
        partial void ExportExcelOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Telia.NTW.Web.ViewModel.Analys.AnalysFilterViewModel filterViewModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult ExportExcel(Telia.NTW.Web.ViewModel.Analys.AnalysFilterViewModel filterViewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ExportExcel);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "filterViewModel", filterViewModel);
            ExportExcelOverride(callInfo, filterViewModel);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009
