// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
#pragma warning disable 1591, 3008, 3009
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Telia.NTW.Web.Controllers
{
    public partial class LeverantörsinformationController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected LeverantörsinformationController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult NioHundraNummer_Edit()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.NioHundraNummer_Edit);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Innehållsleverantör_Edit()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Innehållsleverantör_Edit);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Innehållsleverantör_Inactivate()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Innehållsleverantör_Inactivate);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Get_OrgNr()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Get_OrgNr);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public LeverantörsinformationController Actions { get { return MVC.Leverantörsinformation; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Leverantörsinformation";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Leverantörsinformation";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Telia900Nummer = "Telia900Nummer";
            public readonly string NioHundraNummer_Edit = "NioHundraNummer_Edit";
            public readonly string NioHundraNummer_ExportToExcel = "NioHundraNummer_ExportToExcel";
            public readonly string Innehållsleverantörer = "Innehållsleverantörer";
            public readonly string Innehållsleverantör_Edit = "Innehållsleverantör_Edit";
            public readonly string Innehållsleverantör_Create = "Innehållsleverantör_Create";
            public readonly string Innehållsleverantör_Inactivate = "Innehållsleverantör_Inactivate";
            public readonly string Get_OrgNr = "Get_OrgNr";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Telia900Nummer = "Telia900Nummer";
            public const string NioHundraNummer_Edit = "NioHundraNummer_Edit";
            public const string NioHundraNummer_ExportToExcel = "NioHundraNummer_ExportToExcel";
            public const string Innehållsleverantörer = "Innehållsleverantörer";
            public const string Innehållsleverantör_Edit = "Innehållsleverantör_Edit";
            public const string Innehållsleverantör_Create = "Innehållsleverantör_Create";
            public const string Innehållsleverantör_Inactivate = "Innehållsleverantör_Inactivate";
            public const string Get_OrgNr = "Get_OrgNr";
        }


        static readonly ActionParamsClass_NioHundraNummer_Edit s_params_NioHundraNummer_Edit = new ActionParamsClass_NioHundraNummer_Edit();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_NioHundraNummer_Edit NioHundraNummer_EditParams { get { return s_params_NioHundraNummer_Edit; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_NioHundraNummer_Edit
        {
            public readonly string nioId = "nioId";
            public readonly string accessNo = "accessNo";
            public readonly string errorMessages = "errorMessages";
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_Innehållsleverantör_Edit s_params_Innehållsleverantör_Edit = new ActionParamsClass_Innehållsleverantör_Edit();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Innehållsleverantör_Edit Innehållsleverantör_EditParams { get { return s_params_Innehållsleverantör_Edit; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Innehållsleverantör_Edit
        {
            public readonly string orgNr = "orgNr";
            public readonly string id = "id";
            public readonly string errorMessages = "errorMessages";
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_Innehållsleverantör_Create s_params_Innehållsleverantör_Create = new ActionParamsClass_Innehållsleverantör_Create();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Innehållsleverantör_Create Innehållsleverantör_CreateParams { get { return s_params_Innehållsleverantör_Create; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Innehållsleverantör_Create
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_Innehållsleverantör_Inactivate s_params_Innehållsleverantör_Inactivate = new ActionParamsClass_Innehållsleverantör_Inactivate();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Innehållsleverantör_Inactivate Innehållsleverantör_InactivateParams { get { return s_params_Innehållsleverantör_Inactivate; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Innehållsleverantör_Inactivate
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_Get_OrgNr s_params_Get_OrgNr = new ActionParamsClass_Get_OrgNr();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Get_OrgNr Get_OrgNrParams { get { return s_params_Get_OrgNr; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Get_OrgNr
        {
            public readonly string orgNr = "orgNr";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _Innehållsleverantör = "_Innehållsleverantör";
                public readonly string _Innehållsleverantörer_List = "_Innehållsleverantörer_List";
                public readonly string _Telia900Nummer_List = "_Telia900Nummer_List";
                public readonly string Index = "Index";
                public readonly string Innehållsleverantör_Create = "Innehållsleverantör_Create";
                public readonly string Innehållsleverantör_Edit = "Innehållsleverantör_Edit";
                public readonly string Innehållsleverantörer = "Innehållsleverantörer";
                public readonly string NioHundraNummer_Edit = "NioHundraNummer_Edit";
                public readonly string Telia900Nummer = "Telia900Nummer";
            }
            public readonly string _Innehållsleverantör = "~/Views/Leverantörsinformation/_Innehållsleverantör.cshtml";
            public readonly string _Innehållsleverantörer_List = "~/Views/Leverantörsinformation/_Innehållsleverantörer_List.cshtml";
            public readonly string _Telia900Nummer_List = "~/Views/Leverantörsinformation/_Telia900Nummer_List.cshtml";
            public readonly string Index = "~/Views/Leverantörsinformation/Index.cshtml";
            public readonly string Innehållsleverantör_Create = "~/Views/Leverantörsinformation/Innehållsleverantör_Create.cshtml";
            public readonly string Innehållsleverantör_Edit = "~/Views/Leverantörsinformation/Innehållsleverantör_Edit.cshtml";
            public readonly string Innehållsleverantörer = "~/Views/Leverantörsinformation/Innehållsleverantörer.cshtml";
            public readonly string NioHundraNummer_Edit = "~/Views/Leverantörsinformation/NioHundraNummer_Edit.cshtml";
            public readonly string Telia900Nummer = "~/Views/Leverantörsinformation/Telia900Nummer.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_LeverantörsinformationController : Telia.NTW.Web.Controllers.LeverantörsinformationController
    {
        public T4MVC_LeverantörsinformationController() : base(Dummy.Instance) { }

        [NonAction]
        partial void Telia900NummerOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Telia900Nummer()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Telia900Nummer);
            Telia900NummerOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void NioHundraNummer_EditOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, decimal nioId, string accessNo, System.Collections.Generic.List<string> errorMessages);

        [NonAction]
        public override System.Web.Mvc.ActionResult NioHundraNummer_Edit(decimal nioId, string accessNo, System.Collections.Generic.List<string> errorMessages)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.NioHundraNummer_Edit);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "nioId", nioId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "accessNo", accessNo);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "errorMessages", errorMessages);
            NioHundraNummer_EditOverride(callInfo, nioId, accessNo, errorMessages);
            return callInfo;
        }

        [NonAction]
        partial void NioHundraNummer_EditOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Telia.NTW.Web.ViewModel.Leverantörsinformation.NioHundraNummerRow viewModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult NioHundraNummer_Edit(Telia.NTW.Web.ViewModel.Leverantörsinformation.NioHundraNummerRow viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.NioHundraNummer_Edit);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            NioHundraNummer_EditOverride(callInfo, viewModel);
            return callInfo;
        }

        [NonAction]
        partial void NioHundraNummer_ExportToExcelOverride(T4MVC_Sigma_Utils_ActionResults_ExcelActionResult callInfo);

        [NonAction]
        public override Sigma.Utils.ActionResults.ExcelActionResult NioHundraNummer_ExportToExcel()
        {
            var callInfo = new T4MVC_Sigma_Utils_ActionResults_ExcelActionResult(Area, Name, ActionNames.NioHundraNummer_ExportToExcel);
            NioHundraNummer_ExportToExcelOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void InnehållsleverantörerOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Innehållsleverantörer()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Innehållsleverantörer);
            InnehållsleverantörerOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void Innehållsleverantör_EditOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string orgNr, decimal id, System.Collections.Generic.List<string> errorMessages);

        [NonAction]
        public override System.Web.Mvc.ActionResult Innehållsleverantör_Edit(string orgNr, decimal id, System.Collections.Generic.List<string> errorMessages)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Innehållsleverantör_Edit);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "orgNr", orgNr);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "errorMessages", errorMessages);
            Innehållsleverantör_EditOverride(callInfo, orgNr, id, errorMessages);
            return callInfo;
        }

        [NonAction]
        partial void Innehållsleverantör_EditOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Telia.NTW.Web.ViewModel.Leverantörsinformation.InnehållsleverantörViewModel viewModel, decimal id);

        [NonAction]
        public override System.Web.Mvc.ActionResult Innehållsleverantör_Edit(Telia.NTW.Web.ViewModel.Leverantörsinformation.InnehållsleverantörViewModel viewModel, decimal id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Innehållsleverantör_Edit);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            Innehållsleverantör_EditOverride(callInfo, viewModel, id);
            return callInfo;
        }

        [NonAction]
        partial void Innehållsleverantör_CreateOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Innehållsleverantör_Create()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Innehållsleverantör_Create);
            Innehållsleverantör_CreateOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void Innehållsleverantör_CreateOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Telia.NTW.Web.ViewModel.Leverantörsinformation.InnehållsleverantörViewModel viewModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult Innehållsleverantör_Create(Telia.NTW.Web.ViewModel.Leverantörsinformation.InnehållsleverantörViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Innehållsleverantör_Create);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            Innehållsleverantör_CreateOverride(callInfo, viewModel);
            return callInfo;
        }

        [NonAction]
        partial void Innehållsleverantör_InactivateOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.ActionResult Innehållsleverantör_Inactivate(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Innehållsleverantör_Inactivate);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            Innehållsleverantör_InactivateOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void Get_OrgNrOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string orgNr);

        [NonAction]
        public override System.Web.Mvc.ActionResult Get_OrgNr(string orgNr)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Get_OrgNr);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "orgNr", orgNr);
            Get_OrgNrOverride(callInfo, orgNr);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009
