// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance

using Telia.NTW.Web.ViewModel.Webbstyrning.Multistyrning;
#pragma warning disable 1591, 3008, 3009
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Telia.NTW.Web.Controllers
{
    public partial class MultistyrningController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected MultistyrningController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Index()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Kö_Create()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Kö_Create);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Kö_Edit()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Kö_Edit);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Kö_Delete()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Kö_Delete);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Alternativ_Edit()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Alternativ_Edit);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Alternativ_Delete()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Alternativ_Delete);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public MultistyrningController Actions { get { return MVC.Multistyrning; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Multistyrning";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Multistyrning";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string Index_ExportToExcel = "Index_ExportToExcel";
            public readonly string Kö_Create = "Kö_Create";
            public readonly string Kö_Edit = "Kö_Edit";
            public readonly string Kö_Delete = "Kö_Delete";
            public readonly string Alternativ_Create = "Alternativ_Create";
            public readonly string Alternativ_Edit = "Alternativ_Edit";
            public readonly string Alternativ_Delete = "Alternativ_Delete";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string Index_ExportToExcel = "Index_ExportToExcel";
            public const string Kö_Create = "Kö_Create";
            public const string Kö_Edit = "Kö_Edit";
            public const string Kö_Delete = "Kö_Delete";
            public const string Alternativ_Create = "Alternativ_Create";
            public const string Alternativ_Edit = "Alternativ_Edit";
            public const string Alternativ_Delete = "Alternativ_Delete";
        }


        static readonly ActionParamsClass_Index s_params_Index = new ActionParamsClass_Index();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Index IndexParams { get { return s_params_Index; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Index
        {
            public readonly string errorMessages = "errorMessages";
        }
        static readonly ActionParamsClass_Kö_Create s_params_Kö_Create = new ActionParamsClass_Kö_Create();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Kö_Create Kö_CreateParams { get { return s_params_Kö_Create; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Kö_Create
        {
            public readonly string errorMessages = "errorMessages";
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_Kö_Edit s_params_Kö_Edit = new ActionParamsClass_Kö_Edit();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Kö_Edit Kö_EditParams { get { return s_params_Kö_Edit; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Kö_Edit
        {
            public readonly string multistyrningsköRow = "multistyrningsköRow";
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_Kö_Delete s_params_Kö_Delete = new ActionParamsClass_Kö_Delete();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Kö_Delete Kö_DeleteParams { get { return s_params_Kö_Delete; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Kö_Delete
        {
            public readonly string id = "id";
            public readonly string id2 = "id2";
        }
        static readonly ActionParamsClass_Alternativ_Create s_params_Alternativ_Create = new ActionParamsClass_Alternativ_Create();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Alternativ_Create Alternativ_CreateParams { get { return s_params_Alternativ_Create; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Alternativ_Create
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_Alternativ_Edit s_params_Alternativ_Edit = new ActionParamsClass_Alternativ_Edit();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Alternativ_Edit Alternativ_EditParams { get { return s_params_Alternativ_Edit; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Alternativ_Edit
        {
            public readonly string id = "id";
            public readonly string namn = "namn";
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_Alternativ_Delete s_params_Alternativ_Delete = new ActionParamsClass_Alternativ_Delete();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Alternativ_Delete Alternativ_DeleteParams { get { return s_params_Alternativ_Delete; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Alternativ_Delete
        {
            public readonly string id = "id";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _Alternativ_EditForm = "_Alternativ_EditForm";
                public readonly string _Alternativ_List = "_Alternativ_List";
                public readonly string _Historik = "_Historik";
                public readonly string _Kö_EditForm = "_Kö_EditForm";
                public readonly string _Kö_List = "_Kö_List";
                public readonly string Alternativ_Create = "Alternativ_Create";
                public readonly string Alternativ_Edit = "Alternativ_Edit";
                public readonly string Index = "Index";
                public readonly string Kö_Create = "Kö_Create";
                public readonly string Kö_Edit = "Kö_Edit";
            }
            public readonly string _Alternativ_EditForm = "~/Views/Multistyrning/_Alternativ_EditForm.cshtml";
            public readonly string _Alternativ_List = "~/Views/Multistyrning/_Alternativ_List.cshtml";
            public readonly string _Historik = "~/Views/Multistyrning/_Historik.cshtml";
            public readonly string _Kö_EditForm = "~/Views/Multistyrning/_Kö_EditForm.cshtml";
            public readonly string _Kö_List = "~/Views/Multistyrning/_Kö_List.cshtml";
            public readonly string Alternativ_Create = "~/Views/Multistyrning/Alternativ_Create.cshtml";
            public readonly string Alternativ_Edit = "~/Views/Multistyrning/Alternativ_Edit.cshtml";
            public readonly string Index = "~/Views/Multistyrning/Index.cshtml";
            public readonly string Kö_Create = "~/Views/Multistyrning/Kö_Create.cshtml";
            public readonly string Kö_Edit = "~/Views/Multistyrning/Kö_Edit.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_MultistyrningController : Telia.NTW.Web.Controllers.MultistyrningController
    {
        public T4MVC_MultistyrningController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.Collections.Generic.List<string> errorMessages);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index(System.Collections.Generic.List<string> errorMessages)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "errorMessages", errorMessages);
            IndexOverride(callInfo, errorMessages);
            return callInfo;
        }

        [NonAction]
        partial void Index_ExportToExcelOverride(T4MVC_Sigma_Utils_ActionResults_ExcelActionResult callInfo);

        [NonAction]
        public override Sigma.Utils.ActionResults.ExcelActionResult Index_ExportToExcel()
        {
            var callInfo = new T4MVC_Sigma_Utils_ActionResults_ExcelActionResult(Area, Name, ActionNames.Index_ExportToExcel);
            Index_ExportToExcelOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void Kö_CreateOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.Collections.Generic.List<string> errorMessages);

        [NonAction]
        public override System.Web.Mvc.ActionResult Kö_Create(System.Collections.Generic.List<string> errorMessages)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Kö_Create);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "errorMessages", errorMessages);
            Kö_CreateOverride(callInfo, errorMessages);
            return callInfo;
        }

        [NonAction]
        partial void Kö_CreateOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, MultistyrningsköEditViewModel viewModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult Kö_Create(MultistyrningsköEditViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Kö_Create);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            Kö_CreateOverride(callInfo, viewModel);
            return callInfo;
        }

        [NonAction]
        partial void Kö_EditOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, MultistyrningsköRow multistyrningsköRow);

        [NonAction]
        public override System.Web.Mvc.ActionResult Kö_Edit(MultistyrningsköRow multistyrningsköRow)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Kö_Edit);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "multistyrningsköRow", multistyrningsköRow);
            Kö_EditOverride(callInfo, multistyrningsköRow);
            return callInfo;
        }

        [NonAction]
        partial void Kö_EditOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, MultistyrningsköEditViewModel viewModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult Kö_Edit(MultistyrningsköEditViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Kö_Edit);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            Kö_EditOverride(callInfo, viewModel);
            return callInfo;
        }

        [NonAction]
        partial void Kö_DeleteOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id, string id2);

        [NonAction]
        public override System.Web.Mvc.ActionResult Kö_Delete(int id, string id2)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Kö_Delete);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id2", id2);
            Kö_DeleteOverride(callInfo, id, id2);
            return callInfo;
        }

        [NonAction]
        partial void Alternativ_CreateOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Alternativ_Create()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Alternativ_Create);
            Alternativ_CreateOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void Alternativ_CreateOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Multistyrning_Alternativ_FormViewModel viewModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult Alternativ_Create(Multistyrning_Alternativ_FormViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Alternativ_Create);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            Alternativ_CreateOverride(callInfo, viewModel);
            return callInfo;
        }

        [NonAction]
        partial void Alternativ_EditOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, decimal id, string namn);

        [NonAction]
        public override System.Web.Mvc.ActionResult Alternativ_Edit(decimal id, string namn)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Alternativ_Edit);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "namn", namn);
            Alternativ_EditOverride(callInfo, id, namn);
            return callInfo;
        }

        [NonAction]
        partial void Alternativ_EditOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Multistyrning_Alternativ_FormViewModel viewModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult Alternativ_Edit(Multistyrning_Alternativ_FormViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Alternativ_Edit);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            Alternativ_EditOverride(callInfo, viewModel);
            return callInfo;
        }

        [NonAction]
        partial void Alternativ_DeleteOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult Alternativ_Delete(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Alternativ_Delete);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            Alternativ_DeleteOverride(callInfo, id);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009
