// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
#pragma warning disable 1591, 3008, 3009
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Telia.NTW.Web.Controllers
{
    public partial class SAMLController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected SAMLController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult LocalLogout()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LocalLogout);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public SAMLController Actions { get { return MVC.SAML; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "SAML";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "SAML";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string AssertionConsumerService = "AssertionConsumerService";
            public readonly string SLOService = "SLOService";
            public readonly string LocalLogout = "LocalLogout";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string AssertionConsumerService = "AssertionConsumerService";
            public const string SLOService = "SLOService";
            public const string LocalLogout = "LocalLogout";
        }


        static readonly ActionParamsClass_LocalLogout s_params_LocalLogout = new ActionParamsClass_LocalLogout();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_LocalLogout LocalLogoutParams { get { return s_params_LocalLogout; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_LocalLogout
        {
            public readonly string logoutUrl = "logoutUrl";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
            }
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_SAMLController : Telia.NTW.Web.Controllers.SAMLController
    {
        public T4MVC_SAMLController() : base(Dummy.Instance) { }

        [NonAction]
        partial void AssertionConsumerServiceOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult AssertionConsumerService()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AssertionConsumerService);
            AssertionConsumerServiceOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void SLOServiceOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult SLOService()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SLOService);
            SLOServiceOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void LocalLogoutOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string logoutUrl);

        [NonAction]
        public override System.Web.Mvc.ActionResult LocalLogout(string logoutUrl)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LocalLogout);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "logoutUrl", logoutUrl);
            LocalLogoutOverride(callInfo, logoutUrl);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009
