// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
#pragma warning disable 1591, 3008, 3009
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace T4MVC
{
    public class SharedController
    {

        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _Breadcrumb = "_Breadcrumb";
                public readonly string _DeleteConfirm = "_DeleteConfirm";
                public readonly string _Layout = "_Layout";
                public readonly string _LoginPartial = "_LoginPartial";
                public readonly string _QuickHelp = "_QuickHelp";
                public readonly string Error = "Error";
            }
            public readonly string _Breadcrumb = "~/Views/Shared/_Breadcrumb.cshtml";
            public readonly string _DeleteConfirm = "~/Views/Shared/_DeleteConfirm.cshtml";
            public readonly string _Layout = "~/Views/Shared/_Layout.cshtml";
            public readonly string _LoginPartial = "~/Views/Shared/_LoginPartial.cshtml";
            public readonly string _QuickHelp = "~/Views/Shared/_QuickHelp.cshtml";
            public readonly string Error = "~/Views/Shared/Error.cshtml";
            static readonly _EditorTemplatesClass s_EditorTemplates = new _EditorTemplatesClass();
            public _EditorTemplatesClass EditorTemplates { get { return s_EditorTemplates; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _EditorTemplatesClass
            {
                public readonly string Checkbox = "Checkbox";
                public readonly string CheckboxInList = "CheckboxInList";
                public readonly string EnumRadio = "EnumRadio";
                public readonly string JaNejSwitch = "JaNejSwitch";
                public readonly string Switch = "Switch";
                public readonly string SwitchBase = "SwitchBase";
            }
        }
    }

}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009
